---
include:
- board: nice_nano_v2
  shield: MOKETA
  # snippet:  studio-rpc-usb-uart
  snippet:  zmk-usb-logging
  # cmake-args: -DCONFIG_ZMK_STUDIO=y
- board: nice_nano_v2
  shield: settings_reset
